jobs:
- job: Changelog
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: UseRubyVersion@0
    displayName: 'Use Ruby >= 2.4'

  - bash: |
      gem install github_changelog_generator
      github_changelog_generator punkIRC/punkIRC-test
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'Install dependencies & generate changelog'

  - task: CopyFiles@2
    displayName: 'Copy Changelog'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: 'CHANGELOG.md'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Changelog'
    inputs:
      ArtifactName: Changelog
  
- job: Build
  dependsOn: Changelog
  pool:
    vmImage: vs2017-win2016
  steps:
  - task: gittools.gitversion.gitversion-task.GitVersion@3
    displayName: GitVersion

  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: 'Replace tokens in **/*.properties'
    inputs:
      targetFiles: '**/*.properties'

  - task: Maven@3
    displayName: 'Package'
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: false
      goals: 'clean package'

  - task: CopyFiles@2
    displayName: 'Copy Files'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: 'target/pricefield/*'
      TargetFolder: '$(build.artifactstagingdirectory)'
      CleanTargetFolder: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: punkIRC'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: punkIRC
